swagger: "2.0"
info:
  title: "Gravity Haus Auth Api Documentation"
  version: "1.0.0"
host: 57kiuv9e1j.execute-api.us-east-2.amazonaws.com
basePath: /Prod
schemes:
  - https
securityDefinitions:
  jwt:
    type: apiKey
    name: Authorization
    in: header
paths:
  /create-account:
    post:
      summary: Creates a new account
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          required: true
          type: string
        - in: body
          name: body
          description: Account details to be created
          required: true
          schema:
            type: object
            properties:
              password:
                type: string
              email:
                type: string
              firstName:
                type: string
              lastName:
                type: string
              dateOfBirth:
                type: string
              phoneNumber:
                type: string
              phoneNumberCountryCode:
                type: string
              address1:
                type: string
              postalCode:
                type: string
              city:
                type: string
              state:
                type: string
              familyMembers:
                type: array
                items:
                  type: object
                  properties:
                    email:
                      type: string
              stripeToken:
                type: string
              stripePlanId:
                type: string
              coupon:
                type: string
              referralName:
                type: string
              c1:
                type: string
      responses:
        '200':
          description: Account created successfully
          schema:
            type: object
            properties:
              userId:
                type: string
        '400':
          description: Bad request - invalid input
          schema:
            type: object
            properties:
              error:
                type: string
        '401':
          description: Unauthorized - missing or invalid JWT token
          schema:
            type: object
            properties:
              error:
                type: string
        '500':
          description: Internal server error
          schema:
            type: object
            properties:
              error:
                type: string
