swagger: '2.0'
info:
  title: "Gravity Haus Auth Api Documentation"
  version: 1.0.0
host: 57kiuv9e1j.execute-api.us-east-2.amazonaws.com
basePath: /Prod
schemes:
  - https
paths:
  /login:
    post:
      summary: Login user
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        '200':
          description: Successful login
          schema:
            type: object
            properties:
              token:
                type: string
        '401':
          description: Invalid login credentials
          schema:
            type: object
            properties:
              message:
                type: string
        '500':
          description: Internal server error
          schema:
            type: object
            properties:
              error:
                type: string
securityDefinitions:
  JWTAuth:
    type: apiKey
    name: Authorization
    in: header
