swagger: '2.0'
info:
  title: "Gravity Haus Auth Api Documentation"
  version: '1.0.0'
host: 57kiuv9e1j.execute-api.us-east-2.amazonaws.com
basePath: /Prod
schemes:
  - https
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /remove-family-member:
    post:
      security:
        - Bearer: []
      produces:
        - application/json
      parameters:
        - in: body
          name: RemoveFamilyMemberRequest
          description: Request payload for removing a family member
          required: true
          schema:
            type: object
            properties:
              userId:
                type: string
              accountId:
                type: string
      responses:
        '200':
          description: Success response
        '400':
          description: Missing Required Parameters
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
