swagger: "2.0"
info:
  version: "1.0.0"
  title: "Gravity Haus Auth Api Documentation"
basePath: "/Prod"
host: 57kiuv9e1j.execute-api.us-east-2.amazonaws.com
schemes:
  - "https"
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: Use JWT token starting with Bearer, e.g. Bearer XXXXXXX
paths:
  /upsert-account:
    post:
      summary: "Upsert account details"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "body"
          in: "body"
          description: "Account details to upsert"
          required: true
          schema:
            type: object
            properties:
              id:
                type: string
                example: "123456"
              firstName:
                type: string
                example: "John"
              lastName:
                type: string
                example: "Doe"
              dateOfBirth:
                type: string
                example: "2000-01-01"
              handle:
                type: string
                example: "johndoe"
              verified:
                type: boolean
                example: true
              preferredLocation:
                type: string
                example: "New York, NY"
              preferredIntensity:
                type: string
                example: "High"
      responses:
        200:
          description: "Account upserted successfully"
          schema:
            type: object
            properties:
              account:
                type: object
        401:
          description: "Unauthorized"
        500:
          description: "Internal server error"
      security:
        - Bearer: []
